
 const sample=[
  {
    title: 'Agra Fort',
    description: 'A UNESCO World Heritage site, the Agra Fort is a historical fort located in the city of Agra.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Agra_Fort_in_India.jpg/800px-Agra_Fort_in_India.jpg',
    ticketPrice: 600,
    location: 'Agra Fort, Agra, Uttar Pradesh, India',
    longitude: 78.0485,
    latitude: 27.1751,
    state: 'Uttar Pradesh',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Red Fort',
    description: 'The Red Fort is a historic fortification in the city of Delhi and a UNESCO World Heritage site.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Red_Fort_in_Delhi.jpg/800px-Red_Fort_in_Delhi.jpg',
    ticketPrice: 500,
    location: 'Red Fort, Chandni Chowk, Delhi, India',
    longitude: 77.2345,
    latitude: 28.6562,
    state: 'Delhi',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Jaigarh Fort',
    description: 'Located in Jaipur, Jaigarh Fort is known for its impressive architecture and massive walls.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Jaigarh_Fort.jpg/800px-Jaigarh_Fort.jpg',
    ticketPrice: 100,
    location: 'Jaigarh Fort, Amer, Jaipur, Rajasthan, India',
    longitude: 75.8577,
    latitude: 26.9853,
    state: 'Rajasthan',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Mehrangarh Fort',
    description: 'Mehrangarh Fort in Jodhpur is one of the largest forts in India and is famous for its museum.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Mehrangarh_Fort.jpg/800px-Mehrangarh_Fort.jpg',
    ticketPrice: 200,
    location: 'Mehrangarh Fort, Jodhpur, Rajasthan, India',
    longitude: 73.2869,
    latitude: 26.2952,
    state: 'Rajasthan',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Chittorgarh Fort',
    description: 'Chittorgarh Fort is one of the largest forts in India and a UNESCO World Heritage site.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Chittorgarh_fort.jpg/800px-Chittorgarh_fort.jpg',
    ticketPrice: 200,
    location: 'Chittorgarh, Rajasthan, India',
    longitude: 74.6307,
    latitude: 24.8793,
    state: 'Rajasthan',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Gwalior Fort',
    description: 'Gwalior Fort is a historic fort in Gwalior City known for its stunning architecture and history.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Gwalior_Fort.jpg/800px-Gwalior_Fort.jpg',
    ticketPrice: 300,
    location: 'Gwalior Fort, Gwalior, Madhya Pradesh, India',
    longitude: 78.1834,
    latitude: 26.2183,
    state: 'Madhya Pradesh',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Kumbhalgarh Fort',
    description: 'Kumbhalgarh Fort is known for its massive walls and is a UNESCO World Heritage site.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Kumbhalgarh_Fort.jpg/800px-Kumbhalgarh_Fort.jpg',
    ticketPrice: 100,
    location: 'Kumbhalgarh Fort, Rajasthan, India',
    longitude: 73.3465,
    latitude: 25.1780,
    state: 'Rajasthan',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Jaisalmer Fort',
    description: 'Jaisalmer Fort is one of the largest forts in the world and a UNESCO World Heritage site.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Jaisalmer_Fort_%28Sonar_Qila%29.jpg/800px-Jaisalmer_Fort_%28Sonar_Qila%29.jpg',
    ticketPrice: 250,
    location: 'Jaisalmer Fort, Jaisalmer, Rajasthan, India',
    longitude: 70.9162,
    latitude: 26.9157,
    state: 'Rajasthan',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Landsdowne Fort',
    description: 'A charming little hill station with scenic views, Landsdowne Fort is popular among travelers.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Landsdowne-Fort.jpg/800px-Landsdowne-Fort.jpg',
    ticketPrice: 50,
    location: 'Lansdowne, Uttarakhand, India',
    longitude: 78.6022,
    latitude: 29.4286,
    state: 'Uttarakhand',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Rani Durgavati Fort',
    description: 'Rani Durgavati Fort is a historic fort in the Jabalpur district of Madhya Pradesh.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Rani_Durgavati_Fort.jpg/800px-Rani_Durgavati_Fort.jpg',
    ticketPrice: 100,
    location: 'Jabalpur, Madhya Pradesh, India',
    longitude: 79.9432,
    latitude: 23.1573,
    state: 'Madhya Pradesh',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Ranthambore Fort',
    description: 'A historic fort located in the Ranthambore National Park, famous for its beautiful landscapes.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Ranthambore_Fort_%28Rajasthan%29.jpg/800px-Ranthambore_Fort_%28Rajasthan%29.jpg',
    ticketPrice: 100,
    location: 'Ranthambore, Rajasthan, India',
    longitude: 76.7954,
    latitude: 26.0164,
    state: 'Rajasthan',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Panch Mahal',
    description: 'A stunning five-story palace located in Fatehpur Sikri, known for its architectural beauty.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Panch_Mahal_Fatehpur_Sikri.jpg/800px-Panch_Mahal_Fatehpur_Sikri.jpg',
    ticketPrice: 650,
    location: 'Fatehpur Sikri, Uttar Pradesh, India',
    longitude: 77.6549,
    latitude: 27.0961,
    state: 'Uttar Pradesh',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Feroz Shah Kotla',
    description: 'An ancient fortress in Delhi that has historical and architectural significance.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Feroz_Shah_Kotla.jpg/800px-Feroz_Shah_Kotla.jpg',
    ticketPrice: 100,
    location: 'Feroz Shah Kotla, Delhi, India',
    longitude: 77.2294,
    latitude: 28.6175,
    state: 'Delhi',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Purana Qila',
    description: 'The Purana Qila is one of the oldest forts in Delhi and holds a rich history.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Purana_Qila.jpg/800px-Purana_Qila.jpg',
    ticketPrice: 50,
    location: 'Purana Qila, Delhi, India',
    longitude: 77.2371,
    latitude: 28.6104,
    state: 'Delhi',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Tughlaqabad Fort',
    description: 'An ancient fort in Delhi showcasing Tughlaq architecture and history.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Tughlaqabad_Fort.jpg/800px-Tughlaqabad_Fort.jpg',
    ticketPrice: 20,
    location: 'Tughlaqabad, Delhi, India',
    longitude: 77.2437,
    latitude: 28.5306,
    state: 'Delhi',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Kangra Fort',
    description: 'Kangra Fort is one of the largest forts in the Himalayas and is a symbol of bravery.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Kangra_Fort.jpg/800px-Kangra_Fort.jpg',
    ticketPrice: 60,
    location: 'Kangra, Himachal Pradesh, India',
    longitude: 76.7078,
    latitude: 32.0798,
    state: 'Himachal Pradesh',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  },
  {
    title: 'Fort William',
    description: 'An 18th-century fort in Kolkata, known for its historical significance.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Fort_William_India.jpg/800px-Fort_William_India.jpg',
    ticketPrice: 40,
    location: 'Fort William, Kolkata, West Bengal, India',
    longitude: 88.3440,
    latitude: 22.5602,
    state: 'West Bengal',
    reviews: [],
    category: 'Fort',
    owner: '675d066ca6b63af51a18c31f',
    __v: 0,
    highlight: { istrue: false }
  }
]
  module.exports={data:sample}


  // array of obj of 25 uttrakhand tourest place with some detail in                                                                                          
  //       {title:string ,
  //       description:String,
  //       image:  url string,
  //       ticket price:Number,
  //       location: String,
  //       state :String
  //        owner : 67220945084383bb7da4d9b0}  this format